#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SuperSLiM.Resource", IsApplication=false)]

namespace SuperSLiM
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public static int slm_grid_columnWidth = 2130771974;
			
			// aapt resource value: 0x7f010007
			public static int slm_grid_numColumns = 2130771975;
			
			// aapt resource value: 0x7f010001
			public static int slm_headerDisplay = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int slm_isHeader = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int slm_section_firstPosition = 2130771970;
			
			// aapt resource value: 0x7f010005
			public static int slm_section_headerMarginEnd = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int slm_section_headerMarginStart = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int slm_section_layoutManager = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030009
			public static int auto_fit = 2130903049;
			
			// aapt resource value: 0x7f030000
			public static int end = 2130903040;
			
			// aapt resource value: 0x7f030005
			public static int grid = 2130903045;
			
			// aapt resource value: 0x7f030001
			public static int inline = 2130903041;
			
			// aapt resource value: 0x7f030006
			public static int linear = 2130903046;
			
			// aapt resource value: 0x7f030008
			public static int match_header = 2130903048;
			
			// aapt resource value: 0x7f030002
			public static int overlay = 2130903042;
			
			// aapt resource value: 0x7f030007
			public static int staggered_grid = 2130903047;
			
			// aapt resource value: 0x7f030003
			public static int start = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int sticky = 2130903044;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020001
			public static int ApplicationName = 2130837505;
			
			// aapt resource value: 0x7f020000
			public static int Hello = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] superslim_GridSLM = new int[] {
					2130771974,
					2130771975};
			
			// aapt resource value: 0
			public static int superslim_GridSLM_slm_grid_columnWidth = 0;
			
			// aapt resource value: 1
			public static int superslim_GridSLM_slm_grid_numColumns = 1;
			
			public static int[] superslim_LayoutManager = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public static int superslim_LayoutManager_slm_headerDisplay = 1;
			
			// aapt resource value: 0
			public static int superslim_LayoutManager_slm_isHeader = 0;
			
			// aapt resource value: 2
			public static int superslim_LayoutManager_slm_section_firstPosition = 2;
			
			// aapt resource value: 5
			public static int superslim_LayoutManager_slm_section_headerMarginEnd = 5;
			
			// aapt resource value: 4
			public static int superslim_LayoutManager_slm_section_headerMarginStart = 4;
			
			// aapt resource value: 3
			public static int superslim_LayoutManager_slm_section_layoutManager = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
