#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidDonationsLibrary.Resource", IsApplication=false)]

namespace AndroidDonationsLibrary
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050006
			public static int metro_button_text_style = 2131034118;
			
			// aapt resource value: 0x7f050000
			public static int storehouse_blue = 2131034112;
			
			// aapt resource value: 0x7f050003
			public static int storehouse_blue_dark = 2131034115;
			
			// aapt resource value: 0x7f050001
			public static int storehouse_blue_light = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int storehouse_blue_medium = 2131034114;
			
			// aapt resource value: 0x7f050005
			public static int storehouse_king_purple = 2131034117;
			
			// aapt resource value: 0x7f050004
			public static int storehouse_red = 2131034116;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public static int abs__action_bar_default_height = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int abs__action_bar_icon_vertical_padding = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int abs__action_bar_subtitle_bottom_margin = 2131099650;
			
			// aapt resource value: 0x7f060003
			public static int abs__action_bar_subtitle_text_size = 2131099651;
			
			// aapt resource value: 0x7f060004
			public static int abs__action_bar_subtitle_top_margin = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int abs__action_bar_title_text_size = 2131099653;
			
			// aapt resource value: 0x7f060006
			public static int abs__action_button_min_width = 2131099654;
			
			// aapt resource value: 0x7f060007
			public static int bible_nav_bible_book_grid_cell_padding = 2131099655;
			
			// aapt resource value: 0x7f060008
			public static int bible_nav_bible_book_grid_height = 2131099656;
			
			// aapt resource value: 0x7f060009
			public static int bible_nav_bible_book_grid_horizontal_spacing = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public static int bible_nav_bible_book_grid_vertical_spacing = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public static int bible_nav_bible_book_grid_width = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public static int bible_nav_bible_book_header_side_padding = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public static int bible_nav_bible_book_header_top_padding = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public static int bible_nav_bible_book_scroll_view_padding = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public static int bible_nav_bible_book_text_size = 2131099660;
			
			// aapt resource value: 0x7f060010
			public static int bible_nav_chapter_grid_height = 2131099664;
			
			// aapt resource value: 0x7f060011
			public static int bible_nav_chapter_grid_spacing = 2131099665;
			
			// aapt resource value: 0x7f060012
			public static int bible_nav_chapter_grid_text_size = 2131099666;
			
			// aapt resource value: 0x7f060013
			public static int bible_nav_chapter_grid_width = 2131099667;
			
			// aapt resource value: 0x7f060014
			public static int bible_nav_chapter_horizontal_padding = 2131099668;
			
			// aapt resource value: 0x7f060015
			public static int bible_nav_chapter_vertical_padding = 2131099669;
			
			// aapt resource value: 0x7f060016
			public static int document_nav_drawer_button_spacer = 2131099670;
			
			// aapt resource value: 0x7f060017
			public static int document_nav_drawer_button_text = 2131099671;
			
			// aapt resource value: 0x7f060018
			public static int document_nav_drawer_child_first_button_text = 2131099672;
			
			// aapt resource value: 0x7f060019
			public static int document_nav_drawer_child_second_button_text = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public static int document_nav_drawer_icon_padding = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public static int document_nav_drawer_icon_padding_bible = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public static int document_nav_drawer_icon_spacer = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public static int document_nav_drawer_right_padding = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public static int document_nav_drawer_subheading_text = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public static int document_nav_drawer_width = 2131099679;
			
			// aapt resource value: 0x7f060020
			public static int nav_heading_text_size = 2131099680;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int metro_button_style = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int storehouse_blue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int storehouse_white = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public static int donations__bitcoin = 2131165191;
			
			// aapt resource value: 0x7f070008
			public static int donations__bitcoin_button = 2131165192;
			
			// aapt resource value: 0x7f070006
			public static int donations__bitcoin_stub = 2131165190;
			
			// aapt resource value: 0x7f070001
			public static int donations__flattr = 2131165185;
			
			// aapt resource value: 0x7f070000
			public static int donations__flattr_stub = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public static int donations__flattr_url = 2131165195;
			
			// aapt resource value: 0x7f070009
			public static int donations__flattr_webview = 2131165193;
			
			// aapt resource value: 0x7f070003
			public static int donations__google = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public static int donations__google_android_market_donate_button = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public static int donations__google_android_market_spinner = 2131165196;
			
			// aapt resource value: 0x7f070002
			public static int donations__google_stub = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public static int donations__loading_frame = 2131165194;
			
			// aapt resource value: 0x7f070005
			public static int donations__paypal = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public static int donations__paypal_donate_button = 2131165198;
			
			// aapt resource value: 0x7f070004
			public static int donations__paypal_stub = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int donation__item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int donations__fragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int donations__fragment_bitcoin = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int donations__fragment_flattr = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int donations__fragment_google = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int donations__fragment_paypal = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040016
			public static int ApplicationName = 2130968598;
			
			// aapt resource value: 0x7f040015
			public static int Hello = 2130968597;
			
			// aapt resource value: 0x7f040010
			public static int donations__alert_dialog_no_browser = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public static int donations__alert_dialog_title = 2130968591;
			
			// aapt resource value: 0x7f040011
			public static int donations__bitcoin = 2130968593;
			
			// aapt resource value: 0x7f040012
			public static int donations__bitcoin_description = 2130968594;
			
			// aapt resource value: 0x7f040013
			public static int donations__bitcoin_send_bitcoin_button = 2130968595;
			
			// aapt resource value: 0x7f040014
			public static int donations__bitcoin_toast_copy = 2130968596;
			
			// aapt resource value: 0x7f040001
			public static int donations__button_close = 2130968577;
			
			// aapt resource value: 0x7f040003
			public static int donations__description = 2130968579;
			
			// aapt resource value: 0x7f040002
			public static int donations__flattr = 2130968578;
			
			// aapt resource value: 0x7f040004
			public static int donations__flattr_description = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int donations__google_android_market = 2130968581;
			
			// aapt resource value: 0x7f040008
			public static int donations__google_android_market_description = 2130968584;
			
			// aapt resource value: 0x7f040009
			public static int donations__google_android_market_donate_button = 2130968585;
			
			// aapt resource value: 0x7f040007
			public static int donations__google_android_market_not_supported = 2130968583;
			
			// aapt resource value: 0x7f040006
			public static int donations__google_android_market_not_supported_title = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public static int donations__google_android_market_text = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public static int donations__paypal = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public static int donations__paypal_description = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public static int donations__thanks_dialog = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public static int donations__thanks_dialog_title = 2130968589;
			
			// aapt resource value: 0x7f040000
			public static int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
